package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>IT Directory</title>\r\n");
      out.write("\t\t\t\t<!-- Bootstrap Core CSS -->\r\n");
      out.write("\t\t\t    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t    <!-- MetisMenu CSS -->\r\n");
      out.write("\t\t\t    <link href=\"css/metisMenu.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t    <!-- DataTables CSS -->\r\n");
      out.write("\t\t\t    <link href=\"css/dataTables.bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t    <!-- DataTables Responsive CSS -->\r\n");
      out.write("\t\t\t    <link href=\"css/dataTables.responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t    <!-- Custom CSS -->\r\n");
      out.write("\t\t\t    <link href=\"css/sb-admin-2.css\" rel=\"stylesheet\">\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t <nav class=\"navbar navbar-default navbar-static-top\" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                \r\n");
      out.write("                \t\t<a class=\"navbar-brand\" href=\"list.do\"><div id=\"bigfont\">IT Directory</div></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t <div class=\"row\">\r\n");
      out.write("\t                <div class=\"col-lg-12\">\r\n");
      out.write("\t                    <div class=\"panel panel-default\">\r\n");
      out.write("\t                        \r\n");
      out.write("\t                        <!-- /.panel-heading -->\r\n");
      out.write("\t                        <div class=\"panel-body\">\r\n");
      out.write("\t                            <div class=\"dataTable_wrapper\">\r\n");
      out.write("\t                                <table class=\"table table-striped table-bordered table-hover\" id=\"dataTables-example\">\r\n");
      out.write("\t                                    <thead>\r\n");
      out.write("\t                                        <tr>\r\n");
      out.write("\t                                            <th>Name</th>\r\n");
      out.write("\t                                            <th>Address</th>\r\n");
      out.write("\t                                            <th>Township</th>\r\n");
      out.write("\t                                            <th>Email</th>\r\n");
      out.write("\t                                            <th>Website</th>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                    </thead>\r\n");
      out.write("\t                                    <tbody>\r\n");
      out.write("\t                                        <tr class=\"odd gradeX\">\r\n");
      out.write("\t                                            <td>Ahnanda Net</td>\r\n");
      out.write("\t                                            <td>96, Myeik St., Ward (24)</td>\r\n");
      out.write("\t                                            <td>South Dagon</td>\r\n");
      out.write("\t                                            <td class=\"center\">anandanetinfocom@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"even gradeC\">\r\n");
      out.write("\t                                            <td>Konica Minolta</td>\r\n");
      out.write("\t                                            <td>18/24, Aung San Stadium</td>\r\n");
      out.write("\t                                            <td>Mingalar Taung Nyunt</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.gandamarbussinessolution.com</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"odd gradeA\">\r\n");
      out.write("\t                                            <td>IT Land</td>\r\n");
      out.write("\t                                            <td>149, 38th St., Upper Middle Block</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">itland49@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"even gradeA\">\r\n");
      out.write("\t                                            <td>PC Land</td>\r\n");
      out.write("\t                                            <td>7, Bagan Rd., Shwe Paukkan Ward (21)</td>\r\n");
      out.write("\t                                            <td>North Okkalapa</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"odd gradeA\">\r\n");
      out.write("\t                                            <td>TCL Tycoonland</td>\r\n");
      out.write("\t                                            <td>353, Thudhamar Rd., Near Oak Zanar Bus Stop</td>\r\n");
      out.write("\t                                            <td>North Okkalapa</td>\r\n");
      out.write("\t                                            <td class=\"center\">tycoonlord9@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"even gradeA\">\r\n");
      out.write("\t                                            <td>Technoland</td>\r\n");
      out.write("\t                                            <td>Rm 10, G Flr, Hledan Centre</td>\r\n");
      out.write("\t                                            <td>Kamayut</td>\r\n");
      out.write("\t                                            <td class=\"center\">technoland.hledan@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Technoland</td>\r\n");
      out.write("\t                                            <td>162/170, 36th St., Middle Block</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">technolandmyanmar@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">technoland.com.mm</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Alliance Stars Co., Ltd.</td>\r\n");
      out.write("\t                                            <td>379/383, Bo Aung Kyaw Street</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.alliancestars.biz</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>EZY Infotech Company Limited</td>\r\n");
      out.write("\t                                            <td>P/20, Maha Bandoola St., La Mu Dan Ward,</td>\r\n");
      out.write("\t                                            <td>Dawbon</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Synnex</td>\r\n");
      out.write("\t                                            <td>214, Bogyoke Aung San Road</td>\r\n");
      out.write("\t                                            <td>Pabedan</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.synnex.co.th</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Colour Flex Advertising Co.,Ltd.</td>\r\n");
      out.write("\t                                            <td>18, Bo Sein Hman Street</td>\r\n");
      out.write("\t                                            <td>Bahan</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.colourflexadvertising.com</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>National IT Solutions</td>\r\n");
      out.write("\t                                            <td>3, Pyay Rd., 9 Mile</td>\r\n");
      out.write("\t                                            <td>Mayangone</td>\r\n");
      out.write("\t                                            <td class=\"center\">info@nits.com.mm</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.nits.com.mm</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Royal Ayeyarwaddy Co., Ltd.</td>\r\n");
      out.write("\t                                            <td>7, G Flr, 87th Street</td>\r\n");
      out.write("\t                                            <td>Mingalar Taung Nyunt</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.royal-ayeyarwaddy.com</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>MTG</td>\r\n");
      out.write("\t                                            <td>6, Dana Theiddi St., Ward (8)</td>\r\n");
      out.write("\t                                            <td>Mayangone</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.mtg.com.mm</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Do Do Ko Ko</td>\r\n");
      out.write("\t                                            <td>244/A, Seikkanthar St., Upper Block,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.dodokokomyanmar.com</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Barcode & Ribbon</td>\r\n");
      out.write("\t                                            <td>207, 1st Flr, Seikkanthar St.,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">myanmarbarcode@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.myanmarbarcode.com</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>KMD</td>\r\n");
      out.write("\t                                            <td>174 / 182, Pansoedan St.,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.kmd.com.rg</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Particular Solution</td>\r\n");
      out.write("\t                                            <td>172/174/B, 6th Flr, Banyar Dala Rd., Tharyar Gone Ward,</td>\r\n");
      out.write("\t                                            <td>Mingalar Taung Nyunt</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Myanmar Golden Rock International Co., Ltd.(Canon)\r\n");
      out.write("                                                Computers & Accessories</td>\r\n");
      out.write("\t                                            <td>Bldg 18, 6th Flr, MICT Park, Ward (12),</td>\r\n");
      out.write("\t                                            <td>Hlaing</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>GAll ID Myanmar</td>\r\n");
      out.write("\t                                            <td>Blk 3, B-31, 1st Flr, MICT Park, Hlaing University Compus,</td>\r\n");
      out.write("\t                                            <td>Hlaing</td>\r\n");
      out.write("\t                                            <td class=\"center\">marketing@allid.com.mm</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.allid.com.mm</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Golden Power Technology Co.,Ltd.</td>\r\n");
      out.write("\t                                            <td>15, Baho Rd.,</td>\r\n");
      out.write("\t                                            <td>Sanchaung</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.gpt.mm.com</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Winner Computer Group</td>\r\n");
      out.write("\t                                            <td>200, Shwe Gon Daing (West) 5th St.,</td>\r\n");
      out.write("\t                                            <td>Bahan</td>\r\n");
      out.write("\t                                            <td class=\"center\">winner@wcg.net.mm</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.winnercomputergroup.com</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Myanmar Golden Rock International Co., Ltd. (Canon) Photocopying & Duplicating Machines Sales & Repair</td>\r\n");
      out.write("\t                                            <td>Bldg 18, 6th Flr, MICT Park, Ward (12),</td>\r\n");
      out.write("\t                                            <td>Hlaing</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Marvel Tech</td>\r\n");
      out.write("\t                                            <td>171/ G-3, Seikkanthar St., Middle Block,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">mtc.sawnaing@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>CNP</td>\r\n");
      out.write("\t                                            <td>106, Seikkanthar St., Lower Block,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Thatoe Aung Zeya Co., Ltd.</td>\r\n");
      out.write("\t                                            <td>116, Seikkanthar St.,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Golden Myanmar Apex Co., Ltd.</td>\r\n");
      out.write("\t                                            <td>115 / B, 52nd St.,</td>\r\n");
      out.write("\t                                            <td>Pazundaung</td>\r\n");
      out.write("\t                                            <td class=\"center\">info@apex-mm.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Star Universe</td>\r\n");
      out.write("\t                                            <td>58 / B, Myanma Gon Ye Housing,</td>\r\n");
      out.write("\t                                            <td>Tarmwe</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Colour Star Co., Ltd</td>\r\n");
      out.write("\t                                            <td>97, Seikkanthar St., Lower Block,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">sales@colourstar.com.mm</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Infiniti Int'l Co., Ltd.</td>\r\n");
      out.write("\t                                            <td>S204, 39th St., Middle Block,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">Sales@infiniti-int.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Radiances</td>\r\n");
      out.write("\t                                            <td>253, Seikkanthar St., Upper Block,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">hello@radiances.net</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Royal Smart Co., Ltd.</td>\r\n");
      out.write("\t                                            <td>158,36th St., Middle Block,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">office@smart-myanmar.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Acer (Shwe Lamin Nagar Co., Ltd.)</td>\r\n");
      out.write("\t                                            <td>775, Maha Bandoola Rd., Corner of 14th St.,</td>\r\n");
      out.write("\t                                            <td>Lanmadaw</td>\r\n");
      out.write("\t                                            <td class=\"center\">shwelaminnagar@sln-myanmar.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.Acermyanmar.com</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Avidions Technologies</td>\r\n");
      out.write("\t                                            <td>08-05,Maha Bandoola Rd., Lanmadaw Plaza</td>\r\n");
      out.write("\t                                            <td>Lanmadaw</td>\r\n");
      out.write("\t                                            <td class=\"center\">info@avidions.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.avidions.com</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>B2HD</td>\r\n");
      out.write("\t                                            <td>99, Myanma Gone Yee St.,</td>\r\n");
      out.write("\t                                            <td>Mingalar Taung Nyunt</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Chan Mon</td>\r\n");
      out.write("\t                                            <td>226, Seikkanthar St.,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>ICE</td>\r\n");
      out.write("\t                                            <td>44/45/46/47,Hledan St.,</td>\r\n");
      out.write("\t                                            <td>Lanmadaw</td>\r\n");
      out.write("\t                                            <td class=\"center\">computersales.ice@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>I.T Life</td>\r\n");
      out.write("\t                                            <td>8, Bo Hmu Aung St., Bo Sein Hman Ward,</td>\r\n");
      out.write("\t                                            <td>Bahan</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Intellect</td>\r\n");
      out.write("\t                                            <td>25, Rm 103, 15th Flr, Dhama Zedi Rd., Yuzana Business Tower,</td>\r\n");
      out.write("\t                                            <td>Sanchaung</td>\r\n");
      out.write("\t                                            <td class=\"center\">itconn.1@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>PTA</td>\r\n");
      out.write("\t                                            <td>252, 39th St., Upper Block,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">ptacomputer@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Spring Technologies & Systems Co., Ltd.</td>\r\n");
      out.write("\t                                            <td>96, Bogalay Zay St.,</td>\r\n");
      out.write("\t                                            <td>Botahtaung</td>\r\n");
      out.write("\t                                            <td class=\"center\">sales@spring1997.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.spring1997.com</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>ATG</td>\r\n");
      out.write("\t                                            <td>8, Maha Bandoola St.,</td>\r\n");
      out.write("\t                                            <td>Hlaing Thar Yar</td>\r\n");
      out.write("\t                                            <td class=\"center\">aungtechnologygroup@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Loi Heng International Co., Ltd</td>\r\n");
      out.write("\t                                            <td>272, Seikkanthar St.,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">sales@loiheng.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.loiheng.com\r\n");
      out.write("\t                                            </td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Knowledge Zone Development Co., Ltd</td>\r\n");
      out.write("\t                                            <td>17, 2nd Flr, Pan Chan St., Hledan,</td>\r\n");
      out.write("\t                                            <td>Kamayut</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.knowledgemm.com</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Smart Computer Technology</td>\r\n");
      out.write("\t                                            <td>160, 36th St.,/td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Cyber Trade</td>\r\n");
      out.write("\t                                            <td>181, G Flr, 38th St., Middle Block, Ward (8),</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeX\">\r\n");
      out.write("\t                                            <td>Monitor City</td>\r\n");
      out.write("\t                                            <td>196, G Flr, 39th St.,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeC\">\r\n");
      out.write("\t                                            <td>Netsys Solutions</td>\r\n");
      out.write("\t                                            <td>36-A, War Dan St.,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">admin@netsys.com.mm</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeC\">\r\n");
      out.write("\t                                            <td>POS Supply Myanmar</td>\r\n");
      out.write("\t                                            <td>126, 2nd Flr, 41st St., Middle Block,</td>\r\n");
      out.write("\t                                            <td>Botahtaung</td>\r\n");
      out.write("\t                                            <td class=\"center\">hr.manacom@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>ATM</td>\r\n");
      out.write("\t                                            <td>Rm 2, Bldg 4, Yankin 4th St., Ward (1),</td>\r\n");
      out.write("\t                                            <td>Yankin</td>\r\n");
      out.write("\t                                            <td class=\"center\">aungthumin87@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeA\">\r\n");
      out.write("\t                                            <td>Ultra Tech</td>\r\n");
      out.write("\t                                            <td>821, Than Thu Mar Rd., Corner of Anawmar St., Ward (13),</td>\r\n");
      out.write("\t                                            <td>South Okkalapa</td>\r\n");
      out.write("\t                                            <td class=\"center\">soe.yannaingtun@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeX\">\r\n");
      out.write("\t                                            <td>Velox</td>\r\n");
      out.write("\t                                            <td>Rm 506, Bldg 16, MICT Park,</td>\r\n");
      out.write("\t                                            <td>Hlaing</td>\r\n");
      out.write("\t                                            <td class=\"center\">veloxtechnology1@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeX\">\r\n");
      out.write("\t                                            <td>Shwe Pyi Aye Projector</td>\r\n");
      out.write("\t                                            <td>13, G Flr, Thazin St., Yae Kyaw Ward,</td>\r\n");
      out.write("\t                                            <td>Pazundaung</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeX\">\r\n");
      out.write("\t                                            <td>Iventure Computer City</td>\r\n");
      out.write("\t                                            <td>187, Seikkanthar St.,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">iventure.cs@gmail.com</td>\r\n");
      out.write("\t                                            <td class=\"center\">http://www.iventurecc.com.mm</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeC\">\r\n");
      out.write("\t                                            <td>Mega Tech</td>\r\n");
      out.write("\t                                            <td>185, 38th St., Middle Block,</td>\r\n");
      out.write("\t                                            <td>Kyauktada</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                        <tr class=\"gradeC\">\r\n");
      out.write("\t                                            <td>SSS</td>\r\n");
      out.write("\t                                            <td>180, Botahtaung Pagoda St.,</td>\r\n");
      out.write("\t                                            <td>Pazundaung</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                            <td class=\"center\">-</td>\r\n");
      out.write("\t                                        </tr>\r\n");
      out.write("\t                                      \r\n");
      out.write("\t                                    </tbody>\r\n");
      out.write("\t                                </table>\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            \r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                        <!-- /.panel-body -->\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <!-- /.panel -->\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <!-- /.col-lg-12 -->\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  <!-- jQuery -->\r\n");
      out.write("    <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Metis Menu Plugin JavaScript -->\r\n");
      out.write("    <script src=\"js/metisMenu.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- DataTables JavaScript -->\r\n");
      out.write("    <script src=\"js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"js/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Theme JavaScript -->\r\n");
      out.write("    <script src=\"js/sb-admin-2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page-Level Demo Scripts - Tables - Use for reference -->\r\n");
      out.write("    <script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        $('#dataTables-example').DataTable({\r\n");
      out.write("                responsive: true\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
